CREATE TABLE IF NOT EXISTS users (
	_id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS exercises (
	_id INTEGER,
	description TEXT,
    duration INTEGER,
    date INTEGER
);
