CREATE TABLE IF NOT EXISTS users (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	_id TEXT UNIQUE,
	username TEXT UNIQUE
);

CREATE TABLE IF NOT EXISTS exercises (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
    _id TEXT,
	description TEXT,
    duration INTEGER,
    date INTEGER
);
